[project]
title = "Preswald Project"
version = "0.1.0"
port = 8501
slug = "preswald-proj-814523"  
entrypoint = "hello.py"    

[branding]
name = "LA Crimes"
logo = "images/logo.png"
favicon = "images/favicon.ico"
primaryColor = "#F89613"

[data.crime_csv]
type = "csv"
path = "data/crime.csv"

[logging]
level = "INFO"  
format = "%(asctime)s - %(name)s - %(levelname)s - %(message)s"